[package]
name = "atividade-6"
version = "0.1.0"
authors = ["KarolinyPessoal <karolinycosta@yahoo.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
